' Developer Express Code Central Example:
' How to programmatically fill a PDF Form with values
' 
' The following example demonstrates how to obtain a list of current fields in a
' PDF Form (via the PdfFormData.GetFieldNames method) and how to apply new field
' values to an existing PDF Form (via the PdfDocumentProcessor.ApplyFormData
' method).
' 
' You can find sample updates and versions for different programming languages here:
' http://www.devexpress.com/example=T210253
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Namespace PdfFormFilling.Properties

    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")>
    Friend NotInheritable Partial Class Settings
        Inherits Global.System.Configuration.ApplicationSettingsBase

        Private Shared defaultInstance As PdfFormFilling.Properties.Settings = CType((Global.System.Configuration.ApplicationSettingsBase.Synchronized(New PdfFormFilling.Properties.Settings())), PdfFormFilling.Properties.Settings)

        Public Shared ReadOnly Property [Default] As Settings
            Get
                Return PdfFormFilling.Properties.Settings.defaultInstance
            End Get
        End Property
    End Class
End Namespace
